export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const R_PASSWORD_CHANGED = "R_PASSWORD_CHANGED";
export const NAME_CHANGED = "NAME_CHANGED";
export const REGISTER_SUCCSESS = "REGISTER_SUCCSESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SAVE_DATA_TO_DB = "SAVE_DATA_TO_DB";




